version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 6603:3306
    volumes:
      - db_data:/var/lib/mysql # map the data to a volume
      # - ./db_data:/var/lib/mysql # map the data locally
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    depends_on:
      - db
    # image: wordpress:5.2-php7.1
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      # locally mapped volumes
     - ./themes:/var/www/html/wp-content/themes/
     - ./plugins:/var/www/html/wp-content/plugins/
     - ./uploads:/var/www/html/wp-content/uploads/
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

volumes:
  # volumes allow data to persist between https://docs.docker.com/compose/wordpress/
  db_data: {} 