version: '3.7'

services:

  db:
    image: mysql:5.7
    restart: always
    # ports:
      # - 6603:3306 # make port accessible with sequel pro.. probably not safe in production!
    volumes:
      - db_data:/var/lib/mysql # map the data to a volume
      # - ./db_data:/var/lib/mysql # map the data locally
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html/ # locally mapped volume
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}  
volumes:
  db_data: {}
# volumes allow data to persist between containers, we can destroy a container and 
# keep the db volume alive so we don't lose any content or have to setup the site again 
# https://docs.docker.com/compose/wordpress/
# https://docs.docker.com/storage/volumes/
