version: '3.3'

services:
  nginx: 
    build:
        context: ./nginx
    depends_on:
      - wordpress
    ports: 
        - 80:80
        - 443:443
    restart: always
    volumes:
        - logs:/var/log/nginx
        - certs:/etc/nginx/ssl
        - certs:/etc/letsencrypt
        - cbroot:/var/www/certbot
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      
  wordpress:
    depends_on:
      - db
    build: .
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  # mailhog for development only
  mailhog:
    image: mailhog/mailhog:latest
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  
  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
  #   volumes:
  #       - certs:/etc/letsencrypt
  #       - cbroot:/var/www/certbot
volumes:
  db_data: {}
  logs: {}
  certs: {}
  cbroot: {}
